### ISSUE TITLE
Cannot insert UUID into database

### ISSUE THREAD

**Issue by ghost** [poggit/libasynql#11]
**Describe the bug**
I tried inserting my uuid into my database but it failed. I got this error:

> [16:55:49] [Server thread/CRITICAL]: RuntimeException: "Unsupported variable type" (EXCEPTION) in "C:/Users/levi/Documents/pocketmine/virions/libasynql_dev-97.phar/src/poggit/libasynql/generic/MysqlStateme
ntImpl" at line 106
code:
-- #    {create
-- #      {players
-- #      :uuid UUID
INSERT INTO players(UUID, first_joined)
VALUES(:uuid, CURRENT_TIMESTAMP
);
-- #      }
-- #   }
-- # }
and when i change UUID into string it gives me the following error.

SQL PREPARE error: Cannot bind value of type object, for query INSERT INTO players
**Expected behavior**
No error. Able to insert uuid into database
**Environment**
OS: Windows 10
PocketMine version:  PocketMine-MP 3.6.2 for Minecraft: Bedrock Edition v1.9.0 (protocol version 332)

**Comment by dries-c** [comment]
UUID isn't a database supported thing as far as I know....

**Comment by ghost** [comment]
Why not

**Comment by ghost** [comment]
Is it better to use name for fetching

**Comment by SOF3** [comment]
Either use $uuid->toString() or $uuid->toBinary(). The raw UUID object is not a value understood by MySQL.
The data type in the .sql declaration is supposed to be a scalar data type, not a specific MySQL data type .

**Comment by SOF3** [comment]
Either use $uuid->toString() or $uuid->toBinary(). The raw UUID object is not a value understood by MySQL.
