### ISSUE TITLE
Query not executed

### ISSUE THREAD

**Issue by justlunix** [poggit/libasynql#112]
**Describe the bug**
I am using `executeGeneric` to try to create a table, but the table is not created. Executing the query manually works just fine.

config.yml
```yaml
database:
  type: mysql
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: revomc
  worker-limit: 2
```

The credentials are correct, using other credentials (i.e. another user or another db) fails.

onEnable
```php
$this->database = libasynql::create($this->revoCore, $this->revoCore->getConfig()->get("database"), [
    "mysql" => "database/setup.sql"
], true);

$this->database->executeGeneric("players.create_table");
$this->database->waitAll();
```

resources/database/setup.sql
```sql
-- #!mysql
-- #{ players
-- #    { create_table
CREATE TABLE
    `players`
(
    `id`         int(10) unsigned NOT NULL AUTO_INCREMENT,
    `uuid`       varchar(255)     NOT NULL,
    `rank`       varchar(255)     NOT NULL,
    `banned_at`  datetime                  DEFAULT NULL,
    `banned_by`  varchar(255)              DEFAULT NULL,
    `created_at` timestamp        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
-- #    }
-- #}
```

The query is loaded just fine and also queued: 
<img width="1507" alt="image" src="https://github.com/poggit/libasynql/assets/66276367/924008e6-48da-4139-911d-9e17f3dc32d7">

The table is just not created (query not executed?). The onSuccess callback is called.

**Expected behavior**
The table should be created.

**Environment**
OS: MacOS 14.0 (23A344)
PocketMine version: 5.13.0

**Comment by Laith98Dev** [comment]
try to debug it like this
```php
$this->database->executeGeneric("players.create_table", [], fn() => $this->getLogger()->info("Query executed"), fn(SqlError $err) => $this->getLogger()->error($err->getMessage()));
```

**Comment by SOF3** [comment]
you can also enable query logging via the APIs on $this->database

**Comment by justlunix** [comment]
Thanks for your replies, though I already did both of the things you said. :)

The onSuccess callback is called (-> no error when executing):
<img width="371" alt="image" src="https://github.com/poggit/libasynql/assets/66276367/e37fa56e-071c-45c9-be10-41b16a2f89bc">


And I already had the query logging on, but now have switched to the actual setLoggingQueries method.

I really don't quite understand why this is happening.


I am running the plugin through pharynx, might that be a problem? (But then how else should I run it lol, I don't see an issue here)

Also, I'm using composer to fetch the virion. Might this be outdated? Is there better way to include the virion, i.e. injecting the latest phar somehow rather than fetching via composer?

**Comment by justlunix** [comment]
I do think that somehow the threading does not work on my machine like it should, or maybe I am missing something. (I'm on an M2 Pro)

For testing purposes (to check if it really isn't a credentials error or sth like that) I edited the virion to run the query right on the mysqli obj after creation: 

\poggit\libasynql\mysqli\MysqliThread::createConn
![image](https://github.com/poggit/libasynql/assets/66276367/997ffe86-2c72-467e-8e52-15b815295a2f)

This works just fine and the table is created. 

Therefore I believe the issue is somewhere in the threading itself and not somewhere in the connection or the query

---

I have also tried using the await generators:

```php
Await::f2c(fn() => yield from $this->database->asyncGeneric("players.create_table"));
```

Same issue here though, nothing is created.

**Comment by justlunix** [comment]
Okay, I've been digging into the virion a bit more and I came to the following conclusion:

libasynql/src/poggit/libasynql/mysqli/MysqliThread.php:127
as well as
libasynql/src/poggit/libasynql/mysqli/MysqliThread.php:153

The results are being passed to `Utils::assumeNotFalse`. I don't understand how this is supposed to work though, because the parameter `$value` is passed as a closure - which to my understanding is never called there. Since the closure is never called, the query is never executed and never prepared?

If I execute directly:

```php
$result = Utils::assumeNotFalse($mysqli->query($query));
```

Everything works as expected and the table (in this case) is created successfully.

The SQLite Thread in this case uses the `ErrorToExceptionHandler` from Pocketmine, which is actually calling the closure. So this seems like a MySQL bug only. 

@SOF3 Am I missing some other logic here? Is there a reason why a closure is being passed and I just can't find where it's executed? If this is actually a bug I'm happy to create a PR for it.

**Comment by justlunix** [comment]
Actually, it seems like https://packagist.org/packages/sof3/libasynql is outdated... It does not seem to be the current master branch. How do I get the latest version?

**Comment by SOF3** [comment]
Are you using dev-master?

**Comment by justlunix** [comment]
Thanks. I'm stupid, should've realized that :)

Using dev-master should work, I'll try that later

**Comment by justlunix** [comment]
Works as it should with dev-master.

**Comment by SOF3** [comment]
I shouuld probably tag a release.
