### ISSUE TITLE
SQLite3 Parameters

### ISSUE THREAD

**Issue by KielKing** [poggit/libasynql#12]
**Describe the bug**
poggit/libasynql/sqlite3/Sqlite3Thread.php on line 83, ``SQLite3Stmt->bindValue()``, third parameter is not set (type), the default is null, therefor every value of the keys in the array would be null
**Sample code**
```php
$this->connector->executeInsert(
    Queries::STATS_SET_TEST,
    [":name" => $player->getName()]
);
```
**Expected behavior**
Parameters should be binded properly and not always set to null
**Environment**
OS:
Win10 
PocketMine version:
3.7.0

**Comment by SOF3** [comment]
The default value of the third parameter is "autodetect", not "null". It won't null the params. Are you sure it's causing problems?

**Comment by KielKing** [comment]
Ah, I didn't know.
But the problem still persists, the value is set to null, I know this because I have this Prepared Statement:
```
-- #  {set
-- #    {test
INSERT OR REPLACE INTO tester (name, test) VALUES (:name, :test);
-- #    }
-- #  }
```
and when I pass this:
```php
$this->connector->executeInsert(
    Queries::STATS_SET_TEST,
    [":name" => $player->getName(), ":test" => 0]
);
```
it throws a NOT NULL constraint failed error

**Comment by KielKing** [comment]
why does this happen? @SOF3

**Comment by SOF3** [comment]
Have you tried `["name" => ` imstead of `[":name" =>`?

**Comment by KielKing** [comment]
yes, I will also show you the table
```
-- #  {init
-- #    {tester
CREATE TABLE IF NOT EXISTS tester (
  name VARCHAR(30) UNIQUE NOT NULL,
  test INT(11) NOT NULL
);
-- #    }
-- #  }
```

**Comment by SOF3** [comment]
Oh. For the INSERT query, you have to declare the args.
```sql
-- #  {set
-- #    {test
-- #        :name string
-- #        :test string
INSERT OR REPLACE INTO tester (name, test) VALUES (:name, :test);
-- #    }
-- #  }
```

**Comment by KielKing** [comment]
thank you, I will try it
