### ISSUE TITLE
Check if the query is done?

### ISSUE THREAD

**Issue by ghost** [poggit/libasynql#14]
is there a way to Check if the query is done?

**Comment by SOF3** [comment]
Make use of the callback. It is not the responsibility of libasynql to help you manage asynchronous programming. You may want to have a look at [await-generator](https://github.com/SOF3/await-generator).

**Comment by rjworks** [comment]
Will await generator work with executechange? I don't see executeChange in the example at all.

**Comment by SOF3** [comment]
Analogous approach works. await-generator is for syntactic sugar of callbacks <-> generators in general. await-generator and libasynql are not directly related to each other.
