### ISSUE TITLE
High CPU on Linux hosts only.

### ISSUE THREAD

**Issue by AlexPads** [poggit/libasynql#22]
**Describe the bug**
Servers running Linux have High CPU usage when a server containing this is running.

**Expected behavior**
CPU to stay at a lower level than what the allocated CPU is for the instances.

**Other Info** 
Me and matcracker looked into this issue on his plugin BedCoreProtect and found that the viron only affects Linux hosts.

**Environment**
OS: Linux Ubuntu 16.04, 18.04, 19.04 CentOS 7
PocketMine versions: 3.0.0 - 3.11.1

**Comment by SOF3** [comment]
I'd be grateful if someone could rewrite the thread communication part with pmmp/snooze.

**Comment by enescaglayan** [comment]
poggit/libasynql#22
