### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by ghost** [poggit/libasynql#27]
**Describe the bug**
I execute on display this error.

**Sample code*
 InvalidArgumentException: "The query players.init has not been loaded" (EXCEPTION) in "virions/libasynql.phar/src/poggit/libasynql/base/DataConnectorImpl" at line 174

**Environment**
OS: Windows 10
PocketMine version: lastest

**Comment by SOF3** [comment]
As the error says, the query players.init hsa not been loaded.

**Comment by ghost** [comment]
How can I load it? It already exists.

**Comment by SOF3** [comment]
The GitHub issue tracker is not a support fourm.
