### ISSUE TITLE
SQLite3 column type unavailable before first fetch

### ISSUE THREAD

**Issue by VoltageMC** [poggit/libasynql#29]
**Describe the bug**
Sqlite files dont load, including piggyauctions and chestshop.

**Sample code**

Undefined offset: 0 in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 120
Fatal error: Uncaught TypeError: Argument 2 passed to muqsit\chestshop\libs\poggit\libasynql\result\SqlColumnInfo::__construct() must be of the type string, null given, called in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php on line 120 and defined in phar:///home/container/plugins/ChestShop.phar/src/muqsit/chestshop/libs/poggit/libasynql/result/SqlColumnInfo.php:37

**Expected behavior**
The sqlite file loading and storing data.

**Environment**
OS: Linux
PocketMine version: 1.12.0

**Comment by SOF3** [comment]
Fixed by #30
