### ISSUE TITLE
Error: "Unsupported variable type" when type is valid.

### ISSUE THREAD

**Issue by ghost** [poggit/libasynql#51]
**Description:**
I am executing a 'Insert' query with 2 string variables. Valid variable types are being passed to those variables, but I am getting a "Unsupported variable type" exception.

**Sample code**
```
public function registerPlayer($player, string $setting): void{
        if($player instanceof Player) $player = $player->getName();
        if(!$this->isPlayerRegistered($player)){
            $this->playerData[strtolower($player)] = ["username" => $player, "setting" => $setting];
            $this->database->executeInsert("manage.register", ["player" => $player, "setting" => $setting]);
        }
    }
```
```
-- #    { register
-- #      :player string
-- #      :setting string
INSERT INTO player_form_settings
VALUES
(
username = :player,
setting = :setting
);
-- #    }
```
```
$this->registerPlayer("Dapro5173", "formui");
```
**Expected behavior**
A row is inserted into the table: username -> Dapro5173, setting -> formui

**Environment**
OS: Windows 10
PocketMine version: 3.18.0

**Comment by SOF3** [comment]
What database type are you using?

**Comment by SOF3** [comment]
Please provide a full error if possible.

**Comment by ghost** [comment]
![Full Error](https://user-images.githubusercontent.com/60823817/111715117-887f1a80-8829-11eb-8afe-39ab4e6e4370.PNG)

I am using MySQL (self hosted, MariaDB).

**Comment by ghost** [comment]
The 'create table' query works fine.

**Comment by SOF3** [comment]
Could you try to modify this and show the value of $variable->getType()?
https://github.com/poggit/libasynql/blob/0192bcd58db0ef25160ec49f309eb2417e4726ac/libasynql/src/poggit/libasynql/generic/MysqlStatementImpl.php#L69

**Comment by ghost** [comment]
'string' is echoed when I do:
```
echo $variable->getType();
```

**Comment by SOF3** [comment]
That'd be strange. This line is supposed to handle that case.
Can you `var_dump()` it and check if it is really `string(6) "string"`?
https://github.com/poggit/libasynql/blob/0192bcd58db0ef25160ec49f309eb2417e4726ac/libasynql/src/poggit/libasynql/generic/MysqlStatementImpl.php#L85

**Comment by ghost** [comment]
I can confirm that it returns string(6) "string".

I was playing around with things and fixed the issue. However, it is passing NULL to the table instead of the strings. Not sure if this is on my end or the virions. (Most likely mine).

**Comment by ghost** [comment]
It is an issue with the virion.

```
$this->database->executeInsert("manage.register", ["player" => "Dapro5173", "setting" => "formui"]);
```
```
-- #    { register
-- #      :player string
-- #      :setting string
INSERT INTO player_form_settings
VALUES
(
username = :player,
setting = :setting
);
```

**Comment by SOF3** [comment]
This doesn't make sense just by reading the code. Could you try to debug why the switch-case with `string` doesn't return?

**Comment by CortexPE** [comment]
Try

```sql
INSERT INTO `player_form_settings` (`username`, `setting`) VALUES (:player,
:setting);
```

**Comment by SOF3** [comment]
that shouldn't affect this bug

**Comment by Muqsit** [comment]
It might be that the \pocketmine\Player import is missing or has a typo in it.

Btw, shouldn't it be `VALUES(:player, :setting)` rather than `VALUES(username = :player, setting = :setting)`?

**Comment by SOF3** [comment]
yes it should be, but that shouldn't cause the crash above.

**Comment by ghost** [comment]
The import is correct. I've tried using: ``VALUES(:player, :setting)`` and it worked. The unsupported variable error no longer shows, so I assume I fixed it without realizing it. Thank you for all your help!

**Comment by SOF3** [comment]
how could that be even relevant...
