### ISSUE TITLE
Warning: Use of unshaded libasynql detected. Debug mode is enabled. This may lead to major performance drop. Please use a shaded package in production. See https://poggit.pmmp.io/virion for more information.

### ISSUE THREAD

**Issue by XDqrkneZ** [poggit/libasynql#6]
```
    /** @var Config */
    public $database;`
` libasynql::create($this, $this->database->get("database"), [
            "mysql" => "mysql.sql",
            "sqlite" => "sqlite3.sql"
        ]);
```
config
```
database:
  type: mysql
  sqlite:
    file: data.sqlite
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: mcpe_test # remember to change this!
worker-limit: 2`
error
```
[20:53:44] [Server thread/CRITICAL]: Error: "Call to a member function get() on null" (EXCEPTION) in "core/src/gay/MainClass" at line 102
```
line 102 on onEnable()
```
        libasynql::create($this, $this->database->get("database"), [
            "mysql" => "mysql.sql",
            "sqlite" => "sqlite3.sql"
        ]);
```

**Comment by Muqsit** [comment]
That is a warning, not an issue. You shouldn't run DEVirion on a production server, inject the virion into the plugin's phar instead because of what the warning said.

**Comment by SOF3** [comment]
You are misusing libasynql.

**Comment by SOF3** [comment]
`$this->database` was not defined. This problem came from your own plugin, and has nothing to do with libasynql.

**Comment by XDqrkneZ** [comment]
```$this->database``` is defined in onEnable() like ```$this->database = new Config($this->getDataFolder()."database.yml",Config::YAML)```

**Comment by SOF3** [comment]
Show all your code

**Comment by TrFolwe** [comment]
When I save data to array in wait function, data is returned as an empty string.

**Comment by TrFolwe** [comment]
I am able to get full result inside array in wait function, Help
