### ISSUE TITLE
New Class Loader changes

### ISSUE THREAD

**Issue by JustSxm** [poggit/libasynql#62]
**Describe the bug**
Class Loader was changed to support registering multiple ClassLoaders to a thread. 
**Sample code**
https://github.com/pmmp/PocketMine-MP/commit/5fbc7681b04fe702fcbd43940b9d325e5c216707
**Expected behavior**
The plugin should work, not crash.

**Environment**
OS: Windows 10
PocketMine version: 4.0.0+dev

**Comment by Ifera** [comment]
Fixed by #63
