### ISSUE TITLE
When I save data to array in wait function, data is returned as an empty string.

### ISSUE THREAD

**Issue by TrFolwe** [poggit/libasynql#67]
**Describe the bug**

**Sample code**

**Expected behavior**

**Environment**
OS:
PocketMine version:

**Comment by TrFolwe** [comment]
When I save data to array in wait function, data is returned as an empty string.

**Comment by TrFolwe** [comment]
When I do this operation inside the Await function, I get a positive result. Help?

**Comment by SOF3** [comment]
Did you see there is an issue template? Edit your main post and fill it in properly, please.

**Comment by SOF3** [comment]
Closed as stale
