### ISSUE TITLE
Add curl options 

### ISSUE THREAD

**Issue by theohdg2** [poggit/libasynql#79]
hello, I open this issue to ask you if in the next update it would be possible to add a curl option like that the developers using the discord/google/facebook api do not lag because for example I use my propore api to retrieve data from my database (security issue :))

Thank you in advance for your reply

**Comment by dries-c** [comment]
It's something completely different than the intended purpose, this might help you out: https://github.com/NetherGamesMC/libasynCurl

**Comment by SOF3** [comment]
liba**s**yn**ql** is for SQL only.

Also there's BulkCurlTask right?
