### ISSUE TITLE
Still causing lag

### ISSUE THREAD

**Issue by SCGamesNetwork** [poggit/libasynql#81]
I use libasynql by using the sample code why is it still lag? even though I have set it in config worker-limit to 5.

**Environment**
OS: Ubuntu 18.04
PocketMine version: 4.3.1

**Comment by SOF3** [comment]
what do you mean by "it still lag"? what exactly did you observe?

**Comment by SCGamesNetwork** [comment]
freezes my server, I can't place blocks and destroy blocks, and can't even move because it freezes, even though my server doesn't have any plugins

**Comment by SOF3** [comment]
if it doesn't have any plugins, how does it have anything to do with libasynql at all?

**Comment by SCGamesNetwork** [comment]
I mean apart from libasynql and my plugins nothing else. and I don't run libasynql in the repeating task or in other tasks.

**Comment by SOF3** [comment]
Seems your plugin uses libasynql incorrectly, or your plugin has some other incorrect code.
