### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dadevguy** [poggit/libasynql#83]
I Think I Got A Bug

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///home/container/plugins/LunarSkyblock.phar/src/Vecnavium/SkyBlocksPM/libs/poggit/libasynql/base/DataConnectorImpl.php on line 166
```

**Comment by Endermanbugzjfc** [comment]
> I Think I Got A Bug
> 
> ```
> Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in phar:///home/container/plugins/LunarSkyblock.phar/src/Vecnavium/SkyBlocksPM/libs/poggit/libasynql/base/DataConnectorImpl.php on line 166
> ```

Your server ran out of memory. This should not be happening. Are you calling a function recursively in tour code?

**Comment by dadevguy** [comment]
hmmm

**Comment by SOF3** [comment]
This seems to be a normal oom error that coincidentally hit when running libasynql. Not an issue of this library.
