### ISSUE TITLE
The link to the mysql example in a plugin does not work

### ISSUE THREAD

**Issue by ghost** [poggit/libasynql#9]

**Comment by Ifera** [comment]
#7

**Comment by Ifera** [comment]
Take a look at why... Also there are a bunch of plugins on poggit which use it so be your own judge i guess...

**Comment by ghost** [comment]
Can you name some of those bunch

**Comment by Ifera** [comment]
How hard is it to go on GitHub search and type libasynql? Surely not that much. Doing so will give you all the plugins/files on github which has the word `libasynql` in it.

**Comment by Ifera** [comment]
Anyways BlockPets, cucumber etc

**Comment by dries-c** [comment]
The NG core :)

**Comment by ghost** [comment]
Why don't you search it up first before telling me to?
