### ISSUE TITLE
PM5 

### ISSUE THREAD

**Issue by royaljacques** [poggit/libasynql#95]
**Describe the bug**
bug with use asyncInsert

```log
Error: "Class "SOFe\AwaitGenerator\Await" not found" (EXCEPTION) in "D:/Codage/Codes/minecraft/pm5/pm5-aetherium/virions/libasynql/src/poggit/libasynql/base/DataConnectorImpl" at line 162
```

**Comment by SOF3** [comment]
don't use DEVirion. compile libasynql into your plugin directly. Tools like [pharynx](https;//GitHub.com/SOF3/pharynx) can help.
