### ISSUE TITLE
SleeperNotifier bug

### ISSUE THREAD

**Issue by Amzy7** [poggit/libasynql#98]
This bug keeps occuring when I try enable the server. (Ive taken the most recent lbasynql)

Error: Too few arguments to function pocketmine\snooze\SleeperNotifier::__construct(), 0 passed in /home/gs-40050/plugins/Orbit Prisons/src/poggit/libasynql/base/SqlThreadPool.php on line 62 and exactly 2 expected
File: pmsrc/vendor/pocketmine/snooze/src/SleeperNotifier

**Environment**
OS: ???
PocketMine version: 5

**Comment by dktapps** [comment]
Use the PM5 branch.
